spring.config.activate.on-profile=prod

spring.application.name=${SPRING_APP_NAME:springsecsection1}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:ERROR}

logging.pattern.console=${LOGPATTERN_CONSOLE::%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_HIBERNATE_FORMAT_SQL:false}

server.servlet.session.timeout=${SESSION_TIMEOUT:10m}

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/eazybankdev

spring.security.oauth2.resourceserver.jwt.jwk-set-uri:${JWK_SET_URI:http://0.0.0.0:8080/realms/eazybankdev/protocol/openid-connect/certs}
